### ISSUE TITLE
GSI integration

### ISSUE THREAD

**Issue by loboda4450** [CM2Walki/CS2#6]
Hello there!

I cannot make cs2 server read GSI config so it could communicate with my API

What I've done:
 - mounted it into `/cs2-dedicated/game/csgo/cfg/gamestate_integration_name.cfg`
 - created this file in  `/cs2-dedicated/game/csgo/cfg/` which is mounted as volume
 - created `steamapps/common/Counter-Strike Global Offensive/csgo/cfg`, put cfg in there and mounted as volume
 - added `-gamestateintegration` env var to extra
 - read whole internet looking for solution :(

I am pretty sure my config is valid, I reach to my API from container.

I am using docker-compose file which is almost identical (less env vars) as this in my pull request there: https://github.com/joedwards32/CS2/pull/36

Thanks in advance.

**Comment by loboda4450** [comment]
Thought that changes in docker-compose are bigger, so posting it there

```
version: '3.7'
services:
  competitive:
    image: cm2network/cs2
    container_name: competitive
    environment:
      - STEAMUSER=steamuser
      - CS2_RCONPW=password
      - CS2_BOT_DIFFICULTY=3
      - CS2_BOT_QUOTA=10
      - CS2_BOT_QUOTA_MODE=competitive
      - CS2_MAPGROUP="mg_active"
      - CS2_STARTMAP="de_inferno"
    volumes:
      - /mnt/cs2/serverdata/:/home/steam/cs2-dedicated/
      - /mnt/cs2/gamestate_integration_gamingroot.cfg:/home/steam/cs2-dedicated/game/csgo/cfg/gamestate_integration_gamingroot.cfg
      - steamcmd_login_volume:/home/steam/Steam
    ports:
      - "27015:27015"
      - "27015:27015/udp"

volumes:
  steamcmd_login_volume:
  ```
